import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbConfig } from "@/utils/dbconfig";
import MainSession from "./MainSession";
import Sider from "./Sider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <MainSession>
        <body className={`${inter.className} flex gap-3`}>
          <Sider />

          <div className="border rounded-md m-4 p-4 w-[calc(100vw-250px)]">
            {children}
          </div>
        </body>
      </MainSession>
    </html>
  );
}
